name = "DD"
uuid = "dbd003b0-366b-4bd7-bab8-1704c0e14406"
authors = ["Hiroyuki Okamura"]
version = "0.5.5"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test"]
doc = ["Documenter"]
